apiVersion: v1
kind: Secret
metadata:
  name: argo-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ghcr.io/argoproj/argo-helm
  name: argo-helm
  type: helm
  enableOCI: "true"
