apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ghcr.io/prometheus-community/charts
  name: kube-prometheus-stack
  type: helm
  enableOCI: "true"