apiVersion: v1
kind: Secret
metadata:
  name: platform-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/agusikprogramusik/platform.git
  name: platform
  type: git
