apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-prometheus-stack
  sources:
    - repoURL: ghcr.io/prometheus-community/charts
      chart: kube-prometheus-stack
      targetRevision: HEAD
      helm:
        valueFiles:
          - $repo/apps/prom-kube-stack/kube-prom-stack-values.yaml
    - repoURL: https://github.com/agusikprogramusik/platform.git
      targetRevision: main
      ref: repo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true