apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - appName: kube-prometheus-stack
            appNamespace: kube-prometheus-stack
            chartRepoURL: ghcr.io/prometheus-community/charts
            chartName: kube-prometheus-stack
            chartVersion: '87.1.0'
            valuesFile: $repo/apps/prom-kube-stack/kube-prom-stack-values.yaml
  template:
    metadata:
      name: '{{ .appName }}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .appNamespace }}'
      sources:
        - repoURL: '{{ .chartRepoURL }}'
          chart: '{{ .chartName }}'
          targetRevision: '{{ .chartVersion }}'
          helm:
            valueFiles:
              - '{{ .valuesFile }}'
        - repoURL: https://github.com/agusikprogramusik/platform.git
          targetRevision: main
          ref: repo
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true