apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - appName: argocd
            appNamespace: argocd
            chartRepoURL: ghcr.io/argoproj/argo-helm
            chartName: argo-cd
            chartVersion: '*'
            valuesFile: $repo/apps/argocd/argocd-values.yaml
  template:
    metadata:
      name: '{{ .appName }}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .appNamespace }}'
      sources:
        - repoURL: '{{ .chartRepoURL }}'
          chart: '{{ .chartName }}'
          targetRevision: '{{ .chartVersion }}'
          helm:
            valueFiles:
              - '{{ .valuesFile }}'
        - repoURL: https://github.com/agusikprogramusik/platform.git
          targetRevision: main
          ref: repo
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true