apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  sources:
    - repoURL: ghcr.io/argoproj/argo-helm
      chart: argo-cd
      targetRevision: 9.5.22
      helm:
        valueFiles:
          - $values/apps/argocd-values.yaml
    - repoURL: https://github.com/agusikprogramusik/platform.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true